import "@/core/interpretator/dom/embedded/logic.deps"
import "@/core/interpretator/dom/embedded/logic.text"
import "@/core/interpretator/dom/embedded/logic.event"
import "@/core/interpretator/dom/embedded/logic.stick"
import "@/core/interpretator/dom/embedded/logic.slot"
import "@/core/interpretator/dom/embedded/logic.list"